[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
