[build]
# Navigate into your React app folder
command = "cd frontend/frontend && npm install --legacy-peer-deps && npm run build"
publish = "frontend/frontend/dist"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
