[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm install --no-audit --no-fund && npm run build"

[functions]
  directory = "frontend/netlify/functions"
  node_bundler = "esbuild"
